#!/bin/bash
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"${PROJECT_ROOT}/tests/check-shell-syntax.sh"
"${PROJECT_ROOT}/tests/test-singbox-init-static.sh"
"${PROJECT_ROOT}/tests/test-runtime-supervisor-static.sh"
"${PROJECT_ROOT}/modules/secrets-management/bin/secret-scan"
"${PROJECT_ROOT}/modules/recovery-verification/tests/test-router-health.sh"
"${PROJECT_ROOT}/modules/dns-catalog-intelligence/tests/test-catalog-review.sh"
"${PROJECT_ROOT}/modules/dns-catalog-intelligence/tests/test-dns-forensics.sh"
"${PROJECT_ROOT}/modules/traffic-observatory/tests/test-router-rollups.sh"
"${PROJECT_ROOT}/modules/traffic-observatory/tests/test-traffic-facts-home-reality.sh"
"${PROJECT_ROOT}/tests/test-dns-query-snapshot.sh"
"${PROJECT_ROOT}/tests/test-traffic-evidence-v3.sh"
"${PROJECT_ROOT}/tests/test-traffic-summary-midnight.sh"
"${PROJECT_ROOT}/modules/ghostroute-health-monitor/tests/test-health-monitor.sh"
"${PROJECT_ROOT}/modules/ghostroute-health-monitor/tests/test-vps-health-monitor.sh"
"${PROJECT_ROOT}/tests/test-deploy-risk.sh"
"${PROJECT_ROOT}/tests/run-console.sh" --fast
"${PROJECT_ROOT}/tests/test-router-access-selection.sh"
"${PROJECT_ROOT}/tests/test-runtime-inventory.sh"
"${PROJECT_ROOT}/tests/test-module-entrypoints.sh"
"${PROJECT_ROOT}/tests/test-docs-port-sanitization.sh"
"${PROJECT_ROOT}/tests/test-channel-a-deploy-static.sh"
"${PROJECT_ROOT}/tests/test-channel-bc-static.sh"
"${PROJECT_ROOT}/tests/test-channel-d-static.sh"
"${PROJECT_ROOT}/tests/test-channel-m-static.sh"
"${PROJECT_ROOT}/tests/test-managed-domain-policy-static.sh"
"${PROJECT_ROOT}/tests/test-dns-policy-split-static.sh"
"${PROJECT_ROOT}/tests/test-managed-split-parity-static.sh"
"${PROJECT_ROOT}/modules/recovery-verification/tests/test-audit-fixes.sh"

echo "fast fixture tests passed"
