#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

assert_contains() {
  local path="$1"
  local pattern="$2"
  if ! rg -n "$pattern" "${PROJECT_ROOT}/${path}" >/dev/null; then
    echo "Expected ${path} to contain pattern: ${pattern}" >&2
    exit 1
  fi
}

assert_not_contains() {
  local path="$1"
  local pattern="$2"
  if rg -n "$pattern" "${PROJECT_ROOT}/${path}" >/dev/null; then
    echo "Expected ${path} not to contain pattern: ${pattern}" >&2
    rg -n "$pattern" "${PROJECT_ROOT}/${path}" >&2
    exit 1
  fi
}

assert_not_contains "ansible/playbooks/10-stealth-vps.yml" 'xray_xhttp'
assert_contains "ansible/playbooks/11-channel-b-vps.yml" 'xray_xhttp'
assert_contains "ansible/playbooks/11-channel-b-vps.yml" 'Channel B Caddy route is present'
assert_not_contains "ansible/playbooks/11-channel-b-vps.yml" 'xray_reality|channel_c_naive|Channel C'
assert_contains "ansible/playbooks/21-channel-b-router.yml" 'channel_b_home_relay'
assert_contains "ansible/playbooks/21-channel-b-router.yml" 'Deploy Channel B home-first XHTTP lane on router'
assert_contains "ansible/playbooks/21-channel-b-router.yml" 'Refresh sing-box rule-sets after catalog deploy'
assert_contains "ansible/playbooks/21-channel-b-router.yml" 'update-singbox-rule-sets.sh --no-restart'
assert_not_contains "ansible/playbooks/21-channel-b-router.yml" 'channel_c|Channel C|NaiveProxy'
assert_contains "ansible/playbooks/12-channel-c-vps.yml" 'caddy_l4'
assert_contains "ansible/playbooks/12-channel-c-vps.yml" 'Channel C Caddy route is present'
assert_not_contains "ansible/playbooks/12-channel-c-vps.yml" 'xray_reality|xray_xhttp'
assert_not_contains "ansible/playbooks/20-stealth-router.yml" 'xray_xhttp|channel_c|Channel C|NaiveProxy|XHTTP'
assert_not_contains "ansible/playbooks/20-stealth-router.yml" 'channel_b_home_relay'

assert_contains "ansible/roles/xray_xhttp/defaults/main.yml" 'channel_b_xhttp_enabled: false'
assert_contains "ansible/roles/xray_xhttp/defaults/main.yml" 'ghcr.io/xtls/xray-core:26\.3\.27'
assert_contains "ansible/roles/xray_xhttp/defaults/main.yml" 'channel_b_xhttp_block_udp_443: false'
assert_contains "ansible/roles/xray_xhttp/tasks/main.yml" 'channel_b_xhttp_listen == .127\.0\.0\.1.'
assert_contains "ansible/roles/xray_xhttp/tasks/main.yml" 'channel_b_xhttp_mode == .packet-up.'
assert_contains "ansible/roles/xray_xhttp/templates/config.json.j2" '"network": "udp"'
assert_contains "ansible/roles/xray_xhttp/templates/config.json.j2" '"port": "443"'
assert_contains "ansible/roles/channel_b_home_relay/templates/config.json.j2" '"network": "xhttp"'
assert_contains "ansible/roles/channel_b_home_relay/templates/config.json.j2" '"tag": "channel-b-home-in"'
assert_contains "ansible/roles/channel_b_home_relay/templates/config.json.j2" '"tag": "channel-b-upstream-socks"'
assert_contains "ansible/roles/channel_b_home_relay/tasks/main.yml" 'xray-core'
assert_contains "ansible/roles/singbox_client/templates/config.json.j2" '"tag": "reality-in"'
assert_contains "ansible/roles/singbox_client/templates/config.json.j2" '"tag": "channel-b-relay-socks"'
assert_contains "ansible/roles/singbox_client/templates/config.json.j2" '"sniff": true'
assert_contains "ansible/roles/stealth_routing/templates/stealth-route-init.sh.j2" 'CHANNEL_B_HOME_PORT'
assert_contains "ansible/roles/stealth_routing/templates/stealth-route-init.sh.j2" 'mobile-reality-channel-b-ingress'
assert_contains "ansible/group_vars/routers.yml" 'home_reality_connlimit_above: 500'
assert_contains "ansible/group_vars/routers.yml" 'channel_b_home_connlimit_above: 500'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" 'STEALTH_IPSET_NAME'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" 'extract_stealth_ipset_cidrs'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" 'which ipset'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" '/usr/sbin/ipset'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" '"\$ipset_bin" save "\$STEALTH_IPSET_NAME"'
assert_contains "modules/routing-core/router/update-singbox-rule-sets.sh" 'print \$3 "/32"'
assert_contains "modules/traffic-observatory/bin/traffic-report" '/jffs/scripts/ghostroute-runtime\.env'
assert_contains "modules/traffic-observatory/bin/traffic-report" 'channel-b-relay-socks'

assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'protocols h1 h2'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'matching_timeout \{\{ caddy_l4_matching_timeout'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'forward_proxy'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'reverse_proxy 127\.0\.0\.1:\{\{ channel_c_naive_tinyproxy_local_port'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'channel_c_naive_hide_ip_enabled'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'channel_c_naive_hide_via_enabled'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'channel_c_naive_probe_resistance_enabled'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'channel-c-subscriptions'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'uri strip_prefix /mobile'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'order forward_proxy before file_server'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'file_server'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel_c_naive_backend'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'Ensure Channel C Naive file_server fallback root exists'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel-c-tinyproxy'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel-c-stunnel'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel-c-squid'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-tinyproxy.conf.j2" 'BasicAuth'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-tinyproxy.service.j2" 'tinyproxy -d -c /etc/tinyproxy/channel-c\.conf'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'basic_ncsa_auth'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'https_port'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'connect_timeout .*8 seconds'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'happy_eyeballs_connect_timeout .*250 milliseconds'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'happy_eyeballs_connect_gap .*50 milliseconds'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel-c-tls\.crt'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'Prefer IPv4 for Channel C Squid hostname resolution'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'channel-c-squid-ipv4-egress'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid-ipv4-egress.service.j2" 'ip6tables -C OUTPUT -m owner --uid-owner proxy'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.service.j2" 'channel-c-squid-ipv4-egress\.service'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.conf.j2" 'acl SSL_ports port 5228'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-squid.service.j2" 'squid -N -f /etc/squid/channel-c\.conf'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-stunnel.conf.j2" 'stunnel'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-stunnel.conf.j2" 'channel_c_naive_squid_local_port'
assert_contains "ansible/roles/caddy_l4/templates/channel-c-stunnel.service.j2" 'stunnel4 /etc/stunnel/channel-c\.conf'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'reverse_proxy 127\.0\.0\.1:\{\{ channel_b_xhttp_local_port \}\}'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'log channel_b_xhttp'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'log channel_c_naive'
assert_contains "ansible/roles/caddy_l4/templates/SystemCaddyfile.j2" 'output stdout'
assert_contains "ansible/roles/caddy_l4/tasks/main.yml" 'vpn\|proxy\|xray\|xhttp\|naive'

assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'clients-channel-b'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'clients-channel-c'
assert_contains "ansible/group_vars/vps_stealth.yml" 'channel_c_naive_clients'
assert_contains "ansible/group_vars/routers.yml" 'channel_b_home_relay_enabled'
assert_contains "ansible/group_vars/routers.yml" 'channel_b_home_ingress_port'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" '\{\{ item.name \}\}\.txt'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'outbound-only JSON'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C NaiveProxy URL for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'naive\+\{\{ channel_c_https_proxy_url \}\}'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C HTTPS proxy compatibility URL for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket HTTPS proxy URL for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket add-node URL for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'shadowrocket://add/'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket field import variants for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'fields-host-port-user-pass'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'fields-user-pass-host-port'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'method=connect'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'plugin=none'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket HTTPS proxy config for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket config QR PNG for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket positional HTTPS proxy config for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C Shadowrocket positional config QR PNG for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" '\[Proxy\]'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'tls=true'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'method=connect,tls=true'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'bypass-system = false'
assert_contains "modules/client-profile-factory/docs/client-profiles.md" 'shadowrocket-positional\.conf'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'Render Channel C sing-box Naive outbound JSON for each named client'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" '"type": "naive"'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" ':443'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" '#\{\{ item.name \}\}-naive'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'noalpn'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'h1'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'host=\{\{ channel_b_xhttp_public_host \}\}'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'alpn=h2'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'mode=\{\{ channel_b_xhttp_mode'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" '"mode": \{\{ channel_b_xhttp_mode'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" "replace\\('/', '%2F'\\)"
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'channel_b_home_relay_enabled'
assert_contains "ansible/playbooks/30-generate-client-profiles.yml" 'channel-b-home'
assert_contains "ansible/playbooks/99-verify.yml" 'Channel B home ingress listener is running when enabled'
assert_contains "ansible/playbooks/99-verify.yml" 'Channel B home relay config is XHTTP ingress to local sing-box SOCKS when enabled'
assert_contains "ansible/playbooks/99-verify.yml" 'sing-box static rule-set contains mirrored STEALTH_DOMAINS IPs'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-b-list'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-b-open'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-b-clean'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-c-list'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-c-open'
assert_contains "modules/client-profile-factory/bin/client-profiles" 'channel-c-clean'
assert_contains ".gitignore" 'clients-channel-b'
assert_contains ".gitignore" 'clients-channel-c'

assert_contains "README.md" 'Channel A'
assert_contains "README.md" 'Channel B'
assert_contains "README.md" 'Channel C'
assert_contains "README-ru.md" 'Channel A'
assert_contains "README-ru.md" 'Channel B'
assert_contains "README-ru.md" 'Channel C'
assert_contains "docs/architecture.md" 'Channel A'
assert_contains "docs/architecture.md" 'Channel B'
assert_contains "docs/architecture.md" 'Channel C'
assert_contains "modules/client-profile-factory/docs/client-profiles.md" 'Channel B XHTTP Selected-Client Production Profiles'
assert_contains "modules/client-profile-factory/docs/client-profiles.md" 'Channel C NaiveProxy Planned Compatibility Lane'
assert_contains "modules/routing-core/docs/stealth-channel-implementation-guide.md" 'Channel B selected clients'
assert_contains "modules/routing-core/docs/stealth-channel-implementation-guide.md" 'Channel C planned clients'

echo "channel-b/c static tests passed"
