#!/bin/sh
# Generate sing-box source rule-sets from the same catalogs that populate
# STEALTH_DOMAINS and VPN_STATIC_NETS. Used by mobile Home Reality ingress so
# reality-in follows the same managed-vs-direct split as home LAN traffic.

set -eu

MODE="${1:---no-restart}"
[ "$MODE" = "--no-restart" ] || [ "$MODE" = "--restart-if-changed" ] || {
  echo "Usage: $0 [--no-restart|--restart-if-changed]" >&2
  exit 2
}

SINGBOX_DIR="${SINGBOX_DIR:-/opt/etc/sing-box}"
RULE_DIR="${SINGBOX_RULE_DIR:-${SINGBOX_DIR}/rule-sets}"
DOMAINS_JSON="${SINGBOX_STEALTH_DOMAINS_JSON:-${RULE_DIR}/stealth-domains.json}"
STATIC_JSON="${SINGBOX_STATIC_NETS_JSON:-${RULE_DIR}/stealth-static.json}"
DNSMASQ_VPS_DNS_CONF="${DNSMASQ_VPS_DNS_CONF:-/jffs/configs/dnsmasq-vps-managed.conf.add}"
MANUAL_DNSMASQ="${MANUAL_DNSMASQ:-/jffs/configs/dnsmasq-stealth.conf.add}"
AUTO_DNSMASQ="${AUTO_DNSMASQ:-/jffs/configs/dnsmasq-autodiscovered.conf.add}"
DOMAINS_NO_VPN="${DOMAINS_NO_VPN:-/jffs/configs/domains-no-vpn.txt}"
STATIC_NETS="${STATIC_NETS:-/jffs/configs/router_configuration.static_nets}"
VPS_DNS_FORWARD_HOST="${VPS_DNS_FORWARD_HOST:-127.0.0.1}"
VPS_DNS_FORWARD_PORT="${VPS_DNS_FORWARD_PORT:-15353}"
STEALTH_IPSET_NAME="${STEALTH_IPSET_NAME:-STEALTH_DOMAINS}"
STEALTH_IPSET_SNAPSHOT="${STEALTH_IPSET_SNAPSHOT:-}"
SINGBOX_BIN="${SINGBOX_BIN:-/opt/bin/sing-box}"
SINGBOX_INIT="${SINGBOX_INIT:-/opt/etc/init.d/S99sing-box}"
DNSMASQ_RESTART="${DNSMASQ_RESTART:-service restart_dnsmasq}"

TMP_PREFIX="/tmp/singbox-rule-sets.$$"
DOMAINS_TXT="${TMP_PREFIX}.domains"
DIRECT_DOMAINS_TXT="${TMP_PREFIX}.direct-domains"
VPS_DNS_DOMAINS_TXT="${TMP_PREFIX}.vps-dns-domains"
STATIC_TXT="${TMP_PREFIX}.static"
DOMAINS_NEW="${TMP_PREFIX}.domains.json"
STATIC_NEW="${TMP_PREFIX}.static.json"
DNSMASQ_VPS_DNS_NEW="${TMP_PREFIX}.vps-dns.conf"
CHANGED=0
DNSMASQ_CHANGED=0

cleanup() {
  rm -f "$DOMAINS_TXT" "$DIRECT_DOMAINS_TXT" "$VPS_DNS_DOMAINS_TXT" "$STATIC_TXT" "$DOMAINS_NEW" "$STATIC_NEW" "$DNSMASQ_VPS_DNS_NEW"
}
trap cleanup EXIT

mkdir -p "$RULE_DIR"

extract_stealth_domains() {
  awk -v target_set="STEALTH_DOMAINS" '
    /^ipset=\// {
      line = $0
      sub(/[[:space:]]*#.*/, "", line)
      n = split(line, parts, "/")
      if (n < 3) next
      set_name = parts[n]
      if (set_name != target_set) next
      for (i = 2; i < n; i++) {
        domain = parts[i]
        gsub(/^[.]+/, "", domain)
        gsub(/[[:space:]]/, "", domain)
        if (domain != "" && domain !~ /[*]/) {
          print tolower(domain)
        }
      }
    }
  ' "$@" 2>/dev/null | sort -u
}

extract_static_cidrs() {
  awk '
    {
      sub(/[[:space:]]*#.*/, "", $0)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
      if ($0 ~ /^[0-9A-Fa-f:.]+\/[0-9]+$/) print $0
    }
  ' "$@" 2>/dev/null | sort -u
}

extract_direct_domains() {
  awk '
    {
      sub(/[[:space:]]*#.*/, "", $0)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
      if ($0 == "") next
      gsub(/^[.]+/, "", $0)
      if ($0 !~ /[*]/) print tolower($0)
    }
  ' "$@" 2>/dev/null | sort -u
}

filter_vps_dns_domains() {
  managed_file="$1"
  direct_file="$2"

  awk '
    NR == FNR {
      direct[$0] = 1
      next
    }
    function covered_by_direct(domain, d) {
      return domain == d || domain ~ ("\\." d "$")
    }
    function is_direct(domain, d) {
      for (d in direct) {
        if (covered_by_direct(domain, d)) return 1
      }
      return 0
    }
    function is_ru_domain(domain) {
      return domain ~ /(^|[.])(ru|su|рф)$/
    }
    {
      domain = tolower($0)
      if (domain == "") next
      if (is_ru_domain(domain)) next
      if (is_direct(domain)) next
      print domain
    }
  ' "$direct_file" "$managed_file" | sort -u
}

extract_stealth_ipset_cidrs() {
  {
    ipset_bin="$(which ipset 2>/dev/null || true)"
    if [ -z "$ipset_bin" ] && [ -x /usr/sbin/ipset ]; then
      ipset_bin=/usr/sbin/ipset
    fi
    if [ -n "$ipset_bin" ]; then
      "$ipset_bin" save "$STEALTH_IPSET_NAME" 2>/dev/null || true
    fi
    if [ -n "$STEALTH_IPSET_SNAPSHOT" ] && [ -f "$STEALTH_IPSET_SNAPSHOT" ]; then
      cat "$STEALTH_IPSET_SNAPSHOT"
    fi
  } | awk -v set_name="$STEALTH_IPSET_NAME" '
    $1 == "add" && $2 == set_name && $3 ~ /^[0-9]+(\.[0-9]+){3}$/ {
      print $3 "/32"
    }
  ' | sort -u
}

write_source_rule_set() {
  input_file="$1"
  output_file="$2"
  field_name="$3"

  {
    printf '{\n'
    printf '  "version": 3,\n'
    if [ -s "$input_file" ]; then
      printf '  "rules": [\n'
      printf '    { "%s": [\n' "$field_name"
      awk '
        {
          gsub(/\\/,"\\\\")
          gsub(/"/,"\\\"")
          printf "%s      \"%s\"", (NR == 1 ? "" : ",\n"), $0
        }
        END { if (NR > 0) printf "\n" }
      ' "$input_file"
      printf '    ] }\n'
      printf '  ]\n'
    else
      printf '  "rules": []\n'
    fi
    printf '}\n'
  } > "$output_file"
}

write_dnsmasq_vps_dns() {
  input_file="$1"
  output_file="$2"

  {
    printf '# Generated by update-singbox-rule-sets.sh; do not edit.\n'
    printf '# Managed/foreign DNS only. RU/direct/default domains use normal dnsmasq upstreams.\n'
    awk -v host="$VPS_DNS_FORWARD_HOST" -v port="$VPS_DNS_FORWARD_PORT" '
      {
        printf "server=/%s/%s#%s\n", $0, host, port
      }
    ' "$input_file"
  } > "$output_file"
}

install_if_changed() {
  new_file="$1"
  target_file="$2"

  if [ ! -f "$target_file" ] || ! cmp -s "$new_file" "$target_file"; then
    cp "$new_file" "$target_file"
    CHANGED=1
  fi
}

install_dnsmasq_if_changed() {
  new_file="$1"
  target_file="$2"

  if [ ! -f "$target_file" ] || ! cmp -s "$new_file" "$target_file"; then
    mkdir -p "$(dirname "$target_file")"
    cp "$new_file" "$target_file"
    DNSMASQ_CHANGED=1
  fi
}

extract_stealth_domains "$MANUAL_DNSMASQ" "$AUTO_DNSMASQ" > "$DOMAINS_TXT"
extract_direct_domains "$DOMAINS_NO_VPN" > "$DIRECT_DOMAINS_TXT"
filter_vps_dns_domains "$DOMAINS_TXT" "$DIRECT_DOMAINS_TXT" > "$VPS_DNS_DOMAINS_TXT"
{
  extract_static_cidrs "$STATIC_NETS"
  extract_stealth_ipset_cidrs
} | sort -u > "$STATIC_TXT"

write_source_rule_set "$DOMAINS_TXT" "$DOMAINS_NEW" "domain_suffix"
write_source_rule_set "$STATIC_TXT" "$STATIC_NEW" "ip_cidr"
write_dnsmasq_vps_dns "$VPS_DNS_DOMAINS_TXT" "$DNSMASQ_VPS_DNS_NEW"

install_if_changed "$DOMAINS_NEW" "$DOMAINS_JSON"
install_if_changed "$STATIC_NEW" "$STATIC_JSON"
install_dnsmasq_if_changed "$DNSMASQ_VPS_DNS_NEW" "$DNSMASQ_VPS_DNS_CONF"

domain_count=$(wc -l < "$DOMAINS_TXT" 2>/dev/null | tr -d ' ')
vps_dns_domain_count=$(wc -l < "$VPS_DNS_DOMAINS_TXT" 2>/dev/null | tr -d ' ')
static_count=$(wc -l < "$STATIC_TXT" 2>/dev/null | tr -d ' ')
domain_count=${domain_count:-0}
vps_dns_domain_count=${vps_dns_domain_count:-0}
static_count=${static_count:-0}

echo "sing-box rule-sets: domains=${domain_count}, static=${static_count}, changed=${CHANGED}"
echo "dnsmasq managed VPS DNS: domains=${vps_dns_domain_count}, changed=${DNSMASQ_CHANGED}, target=${DNSMASQ_VPS_DNS_CONF}"

if [ "$MODE" = "--restart-if-changed" ] && [ "$CHANGED" = "1" ]; then
  "$SINGBOX_BIN" check -C "$SINGBOX_DIR" >/dev/null
  "$SINGBOX_INIT" restart
  echo "sing-box restarted after rule-set update"
fi

if [ "$MODE" = "--restart-if-changed" ] && [ "$DNSMASQ_CHANGED" = "1" ]; then
  $DNSMASQ_RESTART
  echo "dnsmasq restarted after managed VPS DNS update"
fi
