FROM caddy:2-builder AS builder
{% if channel_c_naive_enabled | default(false) | bool %}
RUN xcaddy build \
    --with github.com/mholt/caddy-l4 \
    --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive
{% else %}
RUN xcaddy build \
    --with github.com/mholt/caddy-l4
{% endif %}

FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
