---
galaxy_info:
  role_name: stealth_routing
  author: GhostRoute
  description: Project role for router ipset, dnsmasq and firewall routing policy.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: GenericUNIX
      versions: ["all"]
dependencies: []
